# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5dc29600cc9fbb5d0422e67471f77c1522da8dc494716b79f4a56c3978bd6f349471492795bb3bd209b4a60ddf94d7f72b62c63a9145e12b8498ca6aa787b27

test:
  secret_key_base: d1f22459b123bf5ed7fc603d6b7dcc0ee9e9424d1e8d837f443737d8ad4d03bb3efd37f53130e41d7e0a67dc89d1bfa046017eab24573076c72291f96b9cd76f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
